# Clustering Impact Comparison
This notebook compares the search results of the Information Retrieval System with and without cluster-based re-ranking.

In [5]:
import requests
import time
import pandas as pd

SEARCH_API_URL = "http://127.0.0.1:8003/search/"
DATASET_NAME = "lotte/lifestyle/dev" # or 'beir/quora', 'lotte/lifestyle/dev'
QUERY = "what is the best gym exercies" # Example query

## 1. Search without Clustering

In [7]:
payload_no_clustering = {
    "dataset_name": DATASET_NAME,
    "query": QUERY,
    "model_type": "hybrid",
    "enable_cluster_reranking": False
}

start_time = time.time()
response_no_clustering = requests.post(SEARCH_API_URL, json=payload_no_clustering)
end_time = time.time()

time_no_clustering = end_time - start_time
results_no_clustering = response_no_clustering.json()["results"]

df_no_clustering = pd.DataFrame(results_no_clustering)

print(f"Search time without clustering: {time_no_clustering:.4f} seconds")
print("Results without clustering:")
df_no_clustering

Search time without clustering: 0.7382 seconds
Results without clustering:

   doc_id     score  cluster_id
0   63592  0.800000           2
1   69874  0.621575           3
2   94082  0.454031           4
3    1601  0.446719           2
4   65657  0.361637           2
5  231717  0.317038           2
6   72219  0.200000           3
7   71053  0.153846           3
8   72256  0.134229           3
9   48400  0.127803           3

## 2. Search with Clustering

In [8]:
payload_with_clustering = {
    "dataset_name": DATASET_NAME,
    "query": QUERY,
    "model_type": "hybrid",
    "enable_cluster_reranking": True
}

start_time = time.time()
response_with_clustering = requests.post(SEARCH_API_URL, json=payload_with_clustering)
end_time = time.time()

time_with_clustering = end_time - start_time
results_with_clustering = response_with_clustering.json()["results"]

df_with_clustering = pd.DataFrame(results_with_clustering)

print(f"Search time with clustering: {time_with_clustering:.4f} seconds")
print("Results with clustering:")
df_with_clustering

Search time with clustering: 0.6201 seconds
Results with clustering:

   doc_id     score  cluster_id
0   63592  1.800000           2
1    1601  1.446719           2
2   65657  1.361637           2
3  231717  1.317038           2
4   69874  0.621575           3
5   94082  0.454031           4
6   72219  0.200000           3
7   71053  0.153846           3
8   72256  0.134229           3
9   48400  0.127803           3

## 3. Comparison

In [9]:
print(f"Time difference (with - without): {time_with_clustering - time_no_clustering:.4f} seconds")

print("Documents in top 10 without clustering:", set(df_no_clustering["doc_id"]))
print("Documents in top 10 with clustering:", set(df_with_clustering["doc_id"]))

common_docs = set(df_no_clustering["doc_id"]).intersection(set(df_with_clustering["doc_id"]))
print(f"Number of common documents in top 10: {len(common_docs)}")

Time difference (with - without): -0.1181 seconds
Documents in top 10 without clustering: {'94082', '69874', '1601', '72219', '63592', '231717', '65657', '48400', '71053', '72256'}
Documents in top 10 with clustering: {'94082', '69874', '1601', '72219', '231717', '63592', '65657', '48400', '71053', '72256'}
Number of common documents in top 10: 10